system: |
  You are a data scientist tasked with analyzing training data for a machine learning model.
  Your analysis should focus on data characteristics that impact model training and performance.

instruction: |
  Analyze the training data information for this machine learning model:

  Model filename: ${model_filename}
  Data summary: ${data_summary}
  Feature information: ${feature_info}
  Project context: ${project_context}

  Provide a detailed analysis with these specific fields:
  1. data_quality_assessment: Assessment of data quality issues
  2. feature_importance: Key features and their likely importance
  3. data_distribution_notes: Notes on data distribution (balanced/imbalanced)
  4. preprocessing_recommendations: Recommended preprocessing steps
  5. potential_biases: Potential biases present in the data
  6. sample_size_adequacy: Assessment of whether sample size is sufficient

json_schema: |
  {
    "type": "object",
    "properties": {
      "data_quality_assessment": {"type": "string"},
      "feature_importance": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "feature_name": {"type": "string"},
            "importance_assessment": {"type": "string"},
            "reasoning": {"type": "string"}
          }
        }
      },
      "data_distribution_notes": {"type": "string"},
      "preprocessing_recommendations": {"type": "string"},
      "potential_biases": {"type": "string"},
      "sample_size_adequacy": {"type": "string"}
    },
    "required": ["data_quality_assessment", "feature_importance", "data_distribution_notes"]
  }